FROM ubuntu:latest AS build

RUN apt-get update
RUN apt-get install openjdk-17-jdk -y

COPY . ./pactosolucoes

#
WORKDIR ./pactosolucoes


RUN apt-get install maven -y
RUN mvn clean install

FROM openjdk:17-jdk-slim

EXPOSE 8080

COPY --from=build /app/target/pactosolucoes-1.0.0.jar pactosolucoes.jar

ENTRYPOINT [ "java", "-jar", "pactosolucoes.jar" ]